source 'https://rubygems.org'

gem 'bacon'
gem 'haml'
gem 'kramdown'
gem 'nokogiri', '~> 1.10.8'
gem 'sass'
gem 'sequel'
gem 'sqlite3-ruby', '1.2.5'
gem 'sinatra', '~> 1.4'
gem 'sinatra-contrib'
gem 'thin'
gem 'rake'
gem 'byebug'
